### ISSUE TITLE
How to implement remote methods in the Model.ts template?

### ISSUE THREAD

**Issue by kattsushi** [mean-expert-official/generator-fireloop#2]
**What type of issue are you creating?**

 **Question**
What version of this module are you using?

1.0.0-alpha.20
Write other if any:

**Please add a description for your issue:**

How to implement remote methods in the Model.ts template? I think it should be placed optionally and commented an example of how to implement in the model. I'm testing and works perfect with hooks, greetings!

**Comment by kattsushi** [comment]
I already have it ! propose the pull request

**Comment by jonathan-casarrubias** [comment]
Hi @kattsushi I updated the generator to include remote method configs.

Cheers
jon

**Comment by jonathan-casarrubias** [comment]
Hey @kattsushi,

Just to let you know, at the end I decided to use typescript decorators for registering hooks and remote methods

This is an example of the final implementation:

````js
import { Model } from '@mean-expert/model/index';
/**
 * @module Todo
 * @description
 * Write a useful Todo Model description
 **/
@Model({
  hooks: {
    beforeSave: { name: 'before save', type: 'operation' }
  },
  remotes: {
    myRemote: {
      accepts : { arg: 'id', type: 'string', required: true },
      returns : { arg: 'result', type: 'object' },
      http    : { path: '/:id/my-remote', verb: 'get' }
    }
  }
})

class Todo {
  /**
   * @method constructor
   * @description
   * Register model hooks and methods.
   */
  constructor(app: any) {}
  // Example Operation Hook
  static beforeSave(ctx: any, next: Function): void {
    console.log('Todo: Before Save');
    next();
  }
  // Example Remote Method
  static myRemote(id: string, next: Function): void {
    next(null, `My Remote Example: ${id}`);
  }
}

module.exports = Todo;

````

Regards
Jon

**Comment by kattsushi** [comment]
Wow @jhonatan perfect tin his case great idea for to take advantage of typescript im testing and ley you ! Cheers

**Comment by jonathan-casarrubias** [comment]
Cool, I just uploaded this todo app demo here

https://github.com/mean-expert-official/fireloop-todo-example

**Comment by kattsushi** [comment]
what if I would like to, if not agree slightly change the folder structure if possible to have separate source files and files transpilated because pir example in the models folder has a .map and js .json Set aside .ts as many models as you lose some control my recommendation to have a src folder, but what you say? Cheers

**Comment by jonathan-casarrubias** [comment]
Hi @kattsushi, are you running tsc command prior running the app?

When using `$fireloop serve` you don't need to manually compile, and it does transpile the files on the fly, so there should not be js. and js.map files within your common.

Under the hood fireloop serve runs ts-node 

what approach did you take on this? are the js. and js.map files created even though you are using fireloop serve?

**Comment by kattsushi** [comment]
Hi @jonathan-casarrubias no, apparently not me did not work, I had to modify the file nodemo.json like that works
`{
  "verbose": true,
  "ext": "ts,js,ts,json",
  "watch": ["common", "server"],
  "exec": "ts-node .",
  "ignore":[
    "node_modules",
    "sdk"
  ]
}
also happening not find the module module, to work I had to place the path
import {Model
} From '../../node_modules/@mean-expert/model/index';`
