### ISSUE TITLE
not find module @mean-expert/model/index';

### ISSUE THREAD

**Issue by kattsushi** [mean-expert-official/generator-fireloop#4]
o find the module I have to do this
`import` { Model } from '../../node_modules/@mean-expert/model/index';`

that this bug is? It seems to have to do with any option in the tsconfig.json

**Comment by jonathan-casarrubias** [comment]
@kattsushi I believe it may be an issue with the tsconfig or the typescript version

FireLoop installs typescript 2.0.4 but if you have another typescript installed globally may be used instead and if is older may have this issue, anyway... 2 persons are having the same issue, therefore I need to replicate and fix.

I was about to start writing my next blog, but I won't be able until this is fixed.

Thanks for reporting!!!

**Comment by jonathan-casarrubias** [comment]
@kattsushi I have fixed this issue.

You would need to start a new project with fireloop or clone this project: https://github.com/mean-expert-official/fireloop-todo-example

But not sure that will work with an old project.

Cheers
jon
